[FIX] do not include svml with icc on Itanium, it doesn't exist

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8290,7 +8290,60 @@ rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
 	fi
  ;;
 	icc)
+	# check for svml for the vectorizer
+	echo "$as_me:$LINENO: checking whether we have libsvml" >&5
+echo $ECHO_N "checking whether we have libsvml... $ECHO_C" >&6
+	save_LIBS=$LIBS
+	svml_found=no
 	LIBS="$LIBS -lsvml"
+	# we just try to link, because the functions are not well documented
+	# and can change
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+int main() {}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  svml_found=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+	if test .$svml_found = .yes; then
+		echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+	else
+		echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+		LIBS=$save_LIBS
+	fi
 
 	case $target_cpu in
 	Pentium_III)	xflag=K ;;
@@ -8302,6 +8355,7 @@ rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
 	Athlon_XP)	xflag=K ;;
 	Opteron)	xflag=W ;;
 	Athlon_64)	xflag=W ;;
+	Itanium)	;;
 	*)	{ echo "$as_me:$LINENO: WARNING: could not recognize your cpu type, relying on generic optimization" >&5
 echo "$as_me: WARNING: could not recognize your cpu type, relying on generic optimization" >&2;}
 	esac
