Removed the warning about unused functions of gcc.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5769,6 +5769,50 @@ fi
 rm -f conftest.$ac_objext conftest.$ac_ext
 
 
+	echo "$as_me:$LINENO: checking whether the compiler accepts -Wno-unused-function" >&5
+echo $ECHO_N "checking whether the compiler accepts -Wno-unused-function... $ECHO_C" >&6
+	saved_CFLAGS=$CFLAGS
+	CFLAGS="-Wno-unused-function $CFLAGS"
+	cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; CFLAGS=$saved_CFLAGS
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+
+
 	echo "$as_me:$LINENO: checking whether the compiler accepts -Wall" >&5
 echo $ECHO_N "checking whether the compiler accepts -Wall... $ECHO_C" >&6
 	saved_CFLAGS=$CFLAGS
