[CHANGE] configure: Improved error messages.

diff --git a/configure-ac b/configure-ac
--- a/configure-ac
+++ b/configure-ac
@@ -8245,6 +8245,11 @@ rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
 	fi
 
 
+	# on a 64bit machine, set a flag to test for
+	if test .$m = .64; then
+	   	ES_64BIT=1;
+	fi
+
 	# try CPU specific flags
 	if test .$m != .; then
 
@@ -11664,8 +11669,10 @@ _ACEOF
   LIBS="-lefence $LIBS"
 
 else
-  { { echo "$as_me:$LINENO: error: could not link against the efence library" >&5
-echo "$as_me: error: could not link against the efence library" >&2;}
+  { { echo "$as_me:$LINENO: error: could not link against the efence library
+See \`config.log' for more details." >&5
+echo "$as_me: error: could not link against the efence library
+See \`config.log' for more details." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -11713,8 +11720,8 @@ fi
 
 
 	if test .$with_tcl = .no; then
-	   { { echo "$as_me:$LINENO: error: Tcl is required!" >&5
-echo "$as_me: error: Tcl is required!" >&2;}
+	   { { echo "$as_me:$LINENO: error: Tcl is required by ESPResSo!" >&5
+echo "$as_me: error: Tcl is required by ESPResSo!" >&2;}
    { (exit 1); exit 1; }; }
 	elif test .$with_tcl = .yes; then
 		for version in $TCL_VERSION tcl8.5 tcl8.4 tcl8.3 tcl8.2 tcl; do
@@ -11984,13 +11991,39 @@ fi
 	   # Tcl was not found
 	   case $target_os in
 		*darwin*) { echo "$as_me:$LINENO: If you have Tcl installed, make sure that in one of the library paths, e.g. /usr/local/lib,
-	there is a link from lib<tclversion>.dylib to the Tcl library, which usually is
-	/Library/Frameworks/Tcl.framework/Tcl." >&5
+there is a link from lib<tclversion>.dylib to the Tcl library, which usually is
+/Library/Frameworks/Tcl.framework/Tcl." >&5
 echo "$as_me: If you have Tcl installed, make sure that in one of the library paths, e.g. /usr/local/lib,
-	there is a link from lib<tclversion>.dylib to the Tcl library, which usually is
-	/Library/Frameworks/Tcl.framework/Tcl." >&6;} ;;
-		*)	{ { echo "$as_me:$LINENO: error: Tcl library not found!" >&5
-echo "$as_me: error: Tcl library not found!" >&2;}
+there is a link from lib<tclversion>.dylib to the Tcl library, which usually is
+/Library/Frameworks/Tcl.framework/Tcl." >&6;} ;;
+		*)
+if test "$ES_64BIT"; then
+   { echo "$as_me:$LINENO:
+********************************************************************************
+* Note, that you are using a 64bit machine and ESPResSo tries to build a 64bit *
+* binary. Please make sure that you are using a 64bit version of the library!  *
+********************************************************************************" >&5
+echo "$as_me:
+********************************************************************************
+* Note, that you are using a 64bit machine and ESPResSo tries to build a 64bit *
+* binary. Please make sure that you are using a 64bit version of the library!  *
+********************************************************************************" >&6;}
+fi
+
+		   { { echo "$as_me:$LINENO: error:
+********************************************************************************
+* Could not link against the (static) Tcl library (libtcl*.a).                 *
+* Please add the library path to LDFLAGS (e.g. configure LDFLAGS=-L/usr/lib)!  *
+********************************************************************************
+
+See \`config.log' for more details." >&5
+echo "$as_me: error:
+********************************************************************************
+* Could not link against the (static) Tcl library (libtcl*.a).                 *
+* Please add the library path to LDFLAGS (e.g. configure LDFLAGS=-L/usr/lib)!  *
+********************************************************************************
+
+See \`config.log' for more details." >&2;}
    { (exit 1); exit 1; }; } ;;
 		esac
 	fi
@@ -12083,8 +12116,22 @@ echo "${ECHO_T}no" >&6; }
 	if test .$adp_found = .yes; then
   :
 else
-  { { echo "$as_me:$LINENO: error: TCL headers not found. Please add the include path to CPPFLAGS (e.g. configure CPPFLAGS=-I/usr/include/tcl8.4)." >&5
-echo "$as_me: error: TCL headers not found. Please add the include path to CPPFLAGS (e.g. configure CPPFLAGS=-I/usr/include/tcl8.4)." >&2;}
+  { { echo "$as_me:$LINENO: error:
+********************************************************************************
+* Could not find the Tcl header files (tcl.h).                                 *
+* Please add the include path to CPPFLAGS                                      *
+* (e.g. configure CPPFLAGS=-I/usr/include)!                                    *
+********************************************************************************
+
+See \`config.log' for more details." >&5
+echo "$as_me: error:
+********************************************************************************
+* Could not find the Tcl header files (tcl.h).                                 *
+* Please add the include path to CPPFLAGS                                      *
+* (e.g. configure CPPFLAGS=-I/usr/include)!                                    *
+********************************************************************************
+
+See \`config.log' for more details." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -13773,8 +13820,24 @@ echo "$as_me: error: If you have Tk installed, make sure that in one of the libr
 	there is a link from lib<tkversion>.dylib to the Tk library, which usually is
 	/Library/Frameworks/Tk.framework/Tk." >&2;}
    { (exit 1); exit 1; }; } ;;
-			(*)	{ { echo "$as_me:$LINENO: error: Tk library $with_tk not found" >&5
-echo "$as_me: error: Tk library $with_tk not found" >&2;}
+			(*)
+if test "$ES_64BIT"; then
+   { echo "$as_me:$LINENO:
+********************************************************************************
+* Note, that you are using a 64bit machine and ESPResSo tries to build a 64bit *
+* binary. Please make sure that you are using a 64bit version of the library!  *
+********************************************************************************" >&5
+echo "$as_me:
+********************************************************************************
+* Note, that you are using a 64bit machine and ESPResSo tries to build a 64bit *
+* binary. Please make sure that you are using a 64bit version of the library!  *
+********************************************************************************" >&6;}
+fi
+
+			    { { echo "$as_me:$LINENO: error: Tk library $with_tk not found
+See \`config.log' for more details." >&5
+echo "$as_me: error: Tk library $with_tk not found
+See \`config.log' for more details." >&2;}
    { (exit 1); exit 1; }; } ;;
 			esac
 		fi
@@ -14512,8 +14575,32 @@ fi
 		  if test .$fftw2_found = .yes; then
 		     use_fftw=2
 		  elif test .$with_fftw = .yes; then
-		     { { echo "$as_me:$LINENO: error: no FFTW found" >&5
-echo "$as_me: error: no FFTW found" >&2;}
+
+if test "$ES_64BIT"; then
+   { echo "$as_me:$LINENO:
+********************************************************************************
+* Note, that you are using a 64bit machine and ESPResSo tries to build a 64bit *
+* binary. Please make sure that you are using a 64bit version of the library!  *
+********************************************************************************" >&5
+echo "$as_me:
+********************************************************************************
+* Note, that you are using a 64bit machine and ESPResSo tries to build a 64bit *
+* binary. Please make sure that you are using a 64bit version of the library!  *
+********************************************************************************" >&6;}
+fi
+
+		       { { echo "$as_me:$LINENO: error:
+********************************************************************************
+* Could not find FFTW!                                                         *
+********************************************************************************
+
+See \`config.log' for more details." >&5
+echo "$as_me: error:
+********************************************************************************
+* Could not find FFTW!                                                         *
+********************************************************************************
+
+See \`config.log' for more details." >&2;}
    { (exit 1); exit 1; }; }
 		  fi
 		fi
@@ -14743,8 +14830,38 @@ fi
 	fi
 
 		if test .$fftw3_found != .yes; then
-			{ { echo "$as_me:$LINENO: error: could not link against FFTW3, please specify its header and library locations in CPPFLAGS and LDFLAGS" >&5
-echo "$as_me: error: could not link against FFTW3, please specify its header and library locations in CPPFLAGS and LDFLAGS" >&2;}
+
+if test "$ES_64BIT"; then
+   { echo "$as_me:$LINENO:
+********************************************************************************
+* Note, that you are using a 64bit machine and ESPResSo tries to build a 64bit *
+* binary. Please make sure that you are using a 64bit version of the library!  *
+********************************************************************************" >&5
+echo "$as_me:
+********************************************************************************
+* Note, that you are using a 64bit machine and ESPResSo tries to build a 64bit *
+* binary. Please make sure that you are using a 64bit version of the library!  *
+********************************************************************************" >&6;}
+fi
+
+		   { { echo "$as_me:$LINENO: error:
+********************************************************************************
+* Could not find FFTW3!                                                        *
+* Please add the library path to LDFLAGS (e.g. configure LDFLAGS=-L/usr/lib)   *
+* Please add the include path to CPPFLAGS                                      *
+* (e.g. configure CPPFLAGS=-I/usr/include).                                    *
+********************************************************************************
+
+See \`config.log' for more details." >&5
+echo "$as_me: error:
+********************************************************************************
+* Could not find FFTW3!                                                        *
+* Please add the library path to LDFLAGS (e.g. configure LDFLAGS=-L/usr/lib)   *
+* Please add the include path to CPPFLAGS                                      *
+* (e.g. configure CPPFLAGS=-I/usr/include).                                    *
+********************************************************************************
+
+See \`config.log' for more details." >&2;}
    { (exit 1); exit 1; }; }
 		fi
 	elif test .$with_fftw = .2; then
@@ -15111,8 +15228,38 @@ fi
 	fi
 
 		if test .$fftw2_found != .yes; then
-			{ { echo "$as_me:$LINENO: error: could not link against FFTW2, please specify its header and library locations in CPPFLAGS and LDFLAGS" >&5
-echo "$as_me: error: could not link against FFTW2, please specify its header and library locations in CPPFLAGS and LDFLAGS" >&2;}
+
+if test "$ES_64BIT"; then
+   { echo "$as_me:$LINENO:
+********************************************************************************
+* Note, that you are using a 64bit machine and ESPResSo tries to build a 64bit *
+* binary. Please make sure that you are using a 64bit version of the library!  *
+********************************************************************************" >&5
+echo "$as_me:
+********************************************************************************
+* Note, that you are using a 64bit machine and ESPResSo tries to build a 64bit *
+* binary. Please make sure that you are using a 64bit version of the library!  *
+********************************************************************************" >&6;}
+fi
+
+		   { { echo "$as_me:$LINENO: error:
+********************************************************************************
+* Could not find FFTW2!                                                        *
+* Please add the library path to LDFLAGS (e.g. configure LDFLAGS=-L/usr/lib)   *
+* Please add the include path to CPPFLAGS                                      *
+* (e.g. configure CPPFLAGS=-I/usr/include).                                    *
+********************************************************************************
+
+See \`config.log' for more details." >&5
+echo "$as_me: error:
+********************************************************************************
+* Could not find FFTW2!                                                        *
+* Please add the library path to LDFLAGS (e.g. configure LDFLAGS=-L/usr/lib)   *
+* Please add the include path to CPPFLAGS                                      *
+* (e.g. configure CPPFLAGS=-I/usr/include).                                    *
+********************************************************************************
+
+See \`config.log' for more details." >&2;}
    { (exit 1); exit 1; }; }
 		fi
 	elif test .$with_fftw != .no; then
