Made compilation of the ug error-safe.

diff --git a/doc/latexit.sh.in b/doc/latexit.sh.in
--- a/doc/latexit.sh.in
+++ b/doc/latexit.sh.in
@@ -1,22 +1,44 @@
-#!/bin/sh
+#!/bin/sh 
 SRCDIR=$1
 TEXFILE=$2
 TEXINPUTS=.:$SRCDIR:@abs_srcdir@:
 BIBINPUTS=.:$SRCDIR:
 export TEXINPUTS BIBINPUTS
 
+PDFLATEX="@PDFLATEX@ -halt-on-error -interaction=batchmode"
+
 echo "Running LaTeX stage 1..."
-@PDFLATEX@ $TEXFILE > /dev/null
+
+$PDFLATEX $TEXFILE
+EC=$?
+if [ $EC -ne 0 ]; then
+    echo "ERROR: LaTeX stage 1 failed."
+    echo "See LaTeX output in $TEXFILE.log."
+    exit $EC
+fi
+
 if test -e $TEXFILE.ind; then
     echo "Running makeindex..."
-    @MAKEINDEX@ $TEXFILE
+    @MAKEINDEX@ $TEXFILE || exit $?
 fi
 
 echo "Running bibtex..."
-@BIBTEX@ $TEXFILE
+@BIBTEX@ $TEXFILE || exit $?
 
 echo "Running LaTeX stage 2..."
-@PDFLATEX@ $TEXFILE > /dev/null
+$PDFLATEX $TEXFILE 
+EC=$?
+if [ $EC -ne 0 ]; then
+    echo "ERROR: LaTeX stage 2 failed."
+    echo "See LaTeX output in $TEXFILE.log."
+    exit $EC
+fi
 
 echo "Running LaTeX stage 3..."
-@PDFLATEX@ $TEXFILE > /dev/null
+$PDFLATEX $TEXFILE 
+EC=$?
+if [ $EC -ne 0 ]; then
+    echo "ERROR: LaTeX stage 3 failed."
+    echo "See LaTeX output in $TEXFILE.log."
+    exit $EC
+fi
