Configure fixes. Testsuite does not require grep anymore.

diff --git a/testsuite/test.sh.in b/testsuite/test.sh.in
--- a/testsuite/test.sh.in
+++ b/testsuite/test.sh.in
@@ -1,22 +1,61 @@
 #!/bin/sh
 
+usage() {
+    cat <<EOF
+Usage: $0 [-p PROCESSOR] [TESTCASES]...
+  Run TESTCASE on PROCESSOR processors.
+  Instead of specifying PROCESSORS and TESTCASES on the command line,
+  you can set the environment variables TESTCASES and PROCESSORS.
+EOF
+    exit 2
+}
+
+# list of tests that are not supported by this version
+BLACKLIST=nve_pe.tcl
+
 srcdir=@srcdir@
 ESPRESSO=@top_builddir@/Espresso
+#ESPRESSO_SCRIPTS=@top_srcdir@/scripts
+#export ESPRESSO_SCRIPTS
 
-if test -z "$PROCESSORS"; then
-    echo "please specify the processor numbers in PROCESSORS" 1>&2
-    bail=y
-fi
-if test -z "$TESTCASES"; then
-    echo "please specify the testcases to run in TESTCASES" 1>&2
-    bail=y
-fi
-if test -n "$bail"; then
-    exit -1
+# handle processors
+processors=$PROCESSORS
+if test $1 = "-p"; then
+    processors=$2;
+    shift 2;
 fi
 
-# here go the error messages
-errf=_test.sh_error.$$
+# handle testcases
+testcases=$TESTCASES
+if test $# -ge 1; then
+    testcases="$@"
+fi
+
+# check if variables are available
+if test -z "$processors" || test -z "$testcases"; then
+    test -z "$processors" && echo "Processors not specified!"
+    test -z "$testcases" && echo "No testcases specified!"
+    usage
+fi
+
+# check for blacklisted tests
+testcases_old=$testcases
+testcases=
+blacklisted=
+for testcase in $testcases_old; do
+    ignore=
+    for bl_testcase in $BLACKLIST; do
+	if test "$bl_testcase" = "$testcase"; then
+	    ignore=1
+	    break;
+	fi
+    done
+    if ! test "$ignore"; then
+	testcases="$testcases $testcase"
+    else
+	blacklisted="$blacklisted $testcase"
+    fi
+done
 
 # link all files from the src directory to the run directory, if they are not identical
 for file in `ls $srcdir/`; do
@@ -26,48 +65,53 @@ for file in `ls $srcdir/`; do
     fi
 done
 
-# list of tests that are not supported by this version
-blacklist=
-# and what is missing for what test
-missing=
-for np in $PROCESSORS; do
-    for f in $TESTCASES; do
-	ignore=0
-	for ft in $blacklist; do
-	    if test "$ft" = "$f"; then
-		ignore=1;
-		break;
-	    fi
-	done
-	# only not blacklisted tests
-	if test $ignore -eq 0; then
-	    # this is removed if the script runs through
-	    echo "execution of script failed at unexpected point" > $errf
-	    # TODO: Test exit code of script, don't grep
-	    $ESPRESSO $srcdir/$f $np $errf
-	    if test -f $errf; then
-		if @GREP@ -q -e "^not compiled in:" $errf; then
-		    missing="$missing$f: `cat $errf`\n"
-		    blacklist="$blacklist $f"
-		    rm -f $errf
-		else
-		    echo "Testcase $f failed for $np nodes with error `cat $errf`."
-		    rm -f $errf
-		    exit -666
-		fi
-	    fi
-	else
-	    echo "Test $f is blacklisted, ignoring..."
-	fi
+# here go the error messages
+errf=_test.sh_error.$$
+
+# execute the tests
+for np in $processors; do
+    failed=
+    ignored=
+    for testcase in $testcases; do
+	CMD="$ESPRESSO $srcdir/$testcase $np $errf"
+	echo $CMD
+	$CMD
+	case $? in
+	    (0) ;;
+	    (214) ignored="$ignored $testcase";;
+	    (*) failed="$failed $testcase ($np processors)";;
+	esac
     done
+    if test "$failed"; then break; fi
 done
 
-if test "$missing" != ""; then
-    echo -e "\n\n===============================================\n\n"
-    echo -e "                Tests not done:\n                "
-    echo -e $missing
+echo ""
+echo "***************"
+echo "**  SUMMARY  **"
+echo "***************"
+
+if test "$blacklisted"; then
+    echo "BLACKLISTED TESTS:"
+    for testcase in $blacklisted; do
+	echo "  $testcase"
+    done
 fi
 
-echo -e "\n\n===============================================\n\n"
-echo -e "   Congratulations! ESPResSo seems to be ok."
-echo -e "\n\n===============================================\n\n"
+if test "$ignored"; then
+    echo "IGNORED TESTS:"
+    for testcase in $ignored; do
+	echo "  $testcase"
+    done
+fi
+
+if test "$failed"; then
+    echo "FAILED TESTS:"
+    for testcase in $failed; do
+	echo "  $testcase"
+    done
+else
+    echo "All tests were successful!"
+fi
+
+exec test -z $failed
+
